version: "3.6"

services:
    keycloak-server:
        image: quay.io/keycloak/keycloak:latest
        container_name: keycloak
        volumes:
            - ./keycloak/realms:/opt/keycloak/data/import
        environment:
            KC_DB: postgres
            KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
            KC_DB_USERNAME: ${POSTGRES_USERNAME}
            KC_DB_PASSWORD: ${POSTGRES_PASSWORD}

            KC_HOSTNAME: localhost
            KC_HOSTNAME_PORT: 8080
            KC_HOSTNAME_STRICT: false
            KC_HOSTNAME_STRICT_HTTPS: false

            KC_LOG_LEVEL: info
            KC_METRICS_ENABLED: true
            KC_HEALTH_ENABLED: true
            KC_BOOTSTRAP_ADMIN_USERNAME: ${ADMIN_USERNAME}
            KC_BOOTSTRAP_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
        command: start-dev  --import-realm
        depends_on:
            - keycloak-db
        ports:
            - 8080:8080
        env_file:
            - .env

    keycloak-db:
        container_name: ${POSTGRES_HOST}
        image: postgres:15
        volumes:
            - keycloak_data:/var/lib/postgresql/data
        environment:
            POSTGRES_DB: keycloak
            POSTGRES_USER: ${POSTGRES_USERNAME}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        healthcheck:
            test:
                [
                    "CMD",
                    "pg_isready",
                    "-U",
                    "${POSTGRES_USERNAME}",
                    "-d",
                    "keycloak",
                ]
            interval: 10s
            retries: 5
            start_period: 10s
            timeout: 5s
        ports:
            - "5432:${POSTGRES_PORT}"
        env_file:
            - .env

    websocket-server:
        container_name: websocket
        restart: always
        build:
            context: ./websocket
            dockerfile: Dockerfile
        ports:
            - "3000:${PORT}"
        volumes:
            - ./websocket:/usr/src/app
        depends_on:
            - keycloak-server
        env_file:
            - .env

    backend-server:
        container_name: backend
        restart: always
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "4000:${BACKEND_PORT}"
        volumes:
            - ./backend:/usr/src/app
        depends_on:
            keycloak-db:
                condition: service_healthy
        env_file:
            - .env

    # chat-db:
    #     container_name: db
    #     image: postgres:15
    #     volumes:
    #         - chat_data:/var/lib/postgresql/data
    #     environment:
    #         POSTGRES_DB: keycloak
    #         POSTGRES_USER: ${POSTGRES_USERNAME}
    #         POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    #     ports:
    #         - "5432:${POSTGRES_PORT}"
    #     env_file:
    #         - .env

volumes:
    keycloak_data:
